[package]
name = "dark-std"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
time = { version = "0.3", features = ["formatting", "local-offset", "parsing", "serde"] }
crossbeam = { version = "0.8", default-features = false, option = true }
serde = "1.0"
tokio = { version = "1.0", features = ["full"] }